CHANGELOG.md
lib/src/mocktail.dart
pubspec.yaml
test/mocktail_test.dart

**READY**
YES
- **BREAKING** refactor: replace `MocktailFailure` with `TestFailure`
- feat: add `Matcher` support to verify times API

feat!: add Matcher support to verify API

---

CHANGELOG.md
lib/src/mocktail.dart
pubspec.yaml
test/mocktail_test.dart

**READY**
NO
- fix: override toString on MocktailFailure to improve visibility of failure messages (closes #2)

fix: override toString on MocktailFailure to improve visibility of failure messages

---

CHANGELOG.md
README.md
example/main.dart
lib/src/mocktail.dart
pubspec.yaml
test/mocktail_test.dart

**READY**
YES
- **BREAKING** refactor: use `Symbol` rather than `String`
- fix: strict argument matching on verification when arguments are provided (closes #3)

refactor!: v0.0.1-dev.6

---

CHANGELOG.md
README.md
example/main.dart
lib/src/mocktail.dart
pubspec.yaml
test/mocktail_test.dart

**READY**
YES
- **BREAKING** refactor: rename `verify(mock).calls(#member)` to `verify(mock).called(#member)`
- feat: add `any` argument matcher support to `verify` and `calls`
- feat: add `anyThat` argument matcher support to `verify` and `calls`
- feat: support `verify(mock).called(#member).once()`
- feat: support `verify(mock).called(#member).never()`
- feat: improve error messages to include invocation arguments

feat!: v0.0.1-dev.7

---

CHANGELOG.md
lib/src/mocktail.dart
pubspec.yaml
test/mocktail_test.dart

**READY**
NO
- fix: throw `NoSuchMethodError` when arguments match but memberName does not

fix: throw `NoSuchMethodError` when arguments match but memberName does not

---

CHANGELOG.md
lib/src/mocktail.dart
test/mocktail_test.dart

**READY**
NO
- fix: call verification count for specific invocations

fix: call verification count for specific invocations

---

CHANGELOG.md
lib/src/mocktail.dart
pubspec.yaml
test/mocktail_test.dart

**READY**
NO
- fix: verify call count fixes default arguments (named and positional)
- feat: `thenReturn` argument is optional for `VoidCallback` returns.
- `when(cat).calls(#makeSound).thenReturn()`

fix: verify call count fixes default arguments (named and positional)

---

CHANGELOG.md
README.md
lib/src/mocktail.dart
test/mocktail_test.dart

**READY**
NO
- feat: add capture support
```dart
final calculator = MockCalculator();
when(calculator).calls(#sum).thenReturn(0);
expect(calculator.sum(42, 1), equals(42));
final captured = verify(calculator).calls(#sum)
.withArgs(named: {#x: captureAny, #y: captureAny}).captured;
expect(captured.last, equals([42, 1]));
```
```dart
final calculator = MockCalculator();
final isEven = isA<int>().having((x) => x % 2 == 0, 'even', true);
when(calculator).calls(#sum).thenReturn(42);
expect(calculator.sum(42, 1), equals(42));
final captured = verify(calculator).calls(#sum)
.withArgs(named: {#x: captureAnyThat(isEven), #y: 1}).captured;
expect(captured.last, equals([42]));
```

feat: add argument capture support

---

CHANGELOG.md
pubspec.yaml

**READY**
NO
- chore: bump dependencies
- `matcher: ^0.12.10`
- `test: ^1.16.0`

chore: bump dependencies

---

packages/mocktail/CHANGELOG.md
packages/mocktail/pubspec.yaml

**READY**
NO
- chore(mocktail): v0.0.1-dev.12

chore(mocktail): v0.0.1-dev.12

---

packages/mocktail_image_network/CHANGELOG.md
packages/mocktail_image_network/example/pubspec.yaml
packages/mocktail_image_network/lib/src/mocktail_image_network.dart
packages/mocktail_image_network/pubspec.yaml

**READY**
YES
- feat(mocktail_image_network)!: upgrade to mocktail v0.0.2-dev.4

feat(mocktail_image_network)!: upgrade to mocktail v0.0.2-dev.4

---

packages/mocktail/CHANGELOG.md
packages/mocktail/lib/src/_is_invocation.dart
packages/mocktail/pubspec.yaml
packages/mocktail/test/mocktail_test.dart

**READY**
NO
- fix(mocktail): verify use argmatcher from invocation when matcher is not provided

fix(mocktail): verify use argmatcher from invocation when matcher is not provided

---

.github/workflows/mocktail.yaml
packages/mocktail/CHANGELOG.md
packages/mocktail/lib/src/_register_matcher.dart
packages/mocktail/pubspec.yaml
packages/mocktail/test/matcher_test.dart
packages/mocktail/test/mockito_compat/invocation_matcher_test.dart

**READY**
NO
- chore(mocktail): upgrade to test_api: ^0.3.0 (closes #28)
- fix: typo in matcher registration error (`setUpAll`) (closes #30)

chore(mocktail): upgrade to test_api: ^0.3.0

---

packages/mocktail/CHANGELOG.md
packages/mocktail/lib/src/mocktail.dart
packages/mocktail/pubspec.yaml
packages/mocktail/test/mockito_compat/mockito_test.dart
packages/mocktail/test/mocktail_test.dart

**READY**
NO
- feat(mocktail): v0.1.0
- feat: add `Mock.throwOnMissingStub()`
- fix: make `Mock` instances immutable

feat(mocktail): v0.1.0

---

packages/mocktail_image_network/CHANGELOG.md
packages/mocktail_image_network/pubspec.yaml

**READY**
NO
- feat(mocktail_image_network): v0.1.0

feat(mocktail_image_network): v0.1.0

---

packages/mocktail/CHANGELOG.md
packages/mocktail/pubspec.yaml

**READY**
NO
- chore(mocktail): v0.1.1

chore(mocktail): v0.1.1

---

packages/mocktail/CHANGELOG.md
packages/mocktail/pubspec.yaml

**READY**
NO
- feat: improve generic fallback support
- feat: improve error message for missing `registerFallbackValue`

chore(mocktail): v0.1.2

---

packages/mocktail/CHANGELOG.md
packages/mocktail/README.md
packages/mocktail/pubspec.yaml
packages/mocktail/test/mocktail_test.dart

**READY**
NO
- docs: include how it works section in README (closes #24)
- tests: add additional tests for async void stubbing and verification

docs: include how it works section in README

---

packages/mocktail/lib/src/_register_matcher.dart
packages/mocktail/test/matcher_test.dart

**READY**
NO
- fix: add built-in fallback for DateTime (closes #52)

fix: add built-in fallback for DateTime

---

packages/mocktail/CHANGELOG.md
packages/mocktail/pubspec.yaml

chore: v0.1.4

---

packages/mocktail/README.md

**READY**
NO
added FAQ addressing error faking classes to readme

docs: add FAQ addressing error when faking classes

---

packages/mocktail/README.md

**READY**
NO
As the title described

docs: fix typo in mocktail readme

---

packages/mocktail/README.md

**READY**
NO
Added a section to the FAQ in the README on mocking with extension methods.

docs: mock extension methods

---

.github/workflows/mocktail.yaml
packages/mocktail/lib/src/mocktail.dart
packages/mocktail/test/mockito_compat/capture_test.dart
packages/mocktail/test/mockito_compat/verify_test.dart
packages/mocktail/test/mocktail_test.dart

**READY**
NO
- chore(mocktail): dart format

chore(mocktail): dart format

---

.github/workflows/mocktail_image_network.yaml
packages/mocktail_image_network/test/mocktail_image_network_test.dart

**READY**
NO
- chore(mocktail_image_network): use subosito/flutter-action@v1.5.3 and sort imports

chore(mocktail_image_network): use flutter-action@v1.5.3 and sort imports

---

packages/mocktail/lib/src/_invocation_matcher.dart
packages/mocktail/lib/src/mocktail.dart
packages/mocktail/test/mockito_compat/invocation_matcher_test.dart
packages/mocktail/test/mocktail_test.dart

**READY**
NO
- refactor(mocktail): resolve analysis warnings

refactor(mocktail): resolve analysis warnings

---

packages/mocktail/example/main.dart
packages/mocktail/test/mockito_compat/invocation_matcher_test.dart
packages/mocktail/test/mocktail_test.dart

**READY**
NO
- refactor(mocktail): type arg support enhancements
- update example
- add additional tests
- minor internal refactors

refactor(mocktail): type arg support enhancements

---

packages/mocktail/CHANGELOG.md
packages/mocktail/README.md
packages/mocktail/example/main.dart
packages/mocktail/example/pubspec.yaml
packages/mocktail/pubspec.yaml

**READY**
NO
- chore(mocktail): v0.3.0-dev.1

chore(mocktail): v0.3.0-dev.1

---

packages/mocktail_image_network/CHANGELOG.md
packages/mocktail_image_network/pubspec.yaml

**READY**
YES
- chore(mocktail_image_network): v0.3.0-dev.1

chore(mocktail_image_network): v0.3.0-dev.1

---

packages/mocktail/CHANGELOG.md
packages/mocktail/pubspec.yaml

**READY**
NO
- **BREAKING** feat: add support for type argument matching ([#66](https://github.com/felangel/mocktail/issues/66))
- feat: improve verifyNoMoreInteractions failure message ([#118](https://github.com/felangel/mocktail/issues/118))
- docs: improve argument matcher documentation in `README` ([#102](https://github.com/felangel/mocktail/pull/102))
- docs: fix typo in \_registerMatcher inline docs ([#101](https://github.com/felangel/mocktail/pull/101))
- docs: minor snippet fixes in `README` ([#94](https://github.com/felangel/mocktail/pull/94))
- docs: enhance example to illustrate more use cases

chore(mocktail): v0.3.0

---

packages/mocktail_image_network/CHANGELOG.md
packages/mocktail_image_network/pubspec.yaml

**READY**
NO
- chore(mocktail_image_network): v0.3.0

chore(mocktail_image_network): v0.3.0

---

packages/mocktail_image_network/CHANGELOG.md
packages/mocktail_image_network/pubspec.yaml

**READY**
NO
- chore(mocktail_image_network): v0.3.1

chore(mocktail_image_network): v0.3.1

---

.github/workflows/mocktail.yaml

**READY**
NO
- ci(mocktail): fix test step in workflow

ci(mocktail): fix test step in workflow

---

.github/dependabot.yaml

**READY**
NO
- chore: fix dependabot configuration (closes #158)

chore: fix dependabot configuration

---

.github/workflows/mocktail_image_network.yaml
packages/mocktail/analysis_options.yaml
packages/mocktail_image_network/analysis_options.yaml

**READY**
NO
- fix: remove deprecated invariant_booleans lint

fix: remove deprecated invariant_booleans lint

---

README.md
packages/mocktail/README.md
packages/mocktail_image_network/README.md

**READY**
NO
- docs: fix build status badge on README

docs: fix build status badge on README

---

packages/mocktail/lib/mocktail.dart
packages/mocktail/lib/src/fake.dart
packages/mocktail/lib/src/mocktail.dart
packages/mocktail/pubspec.yaml
packages/mocktail/test/src/fake_test.dart

**HOLD**
NO
- refactor(mocktail): remove dependency on `package:test`
- this should resolve constant incompatibilities between `package:analyzer`, `package:test`, and `flutter_test`

refactor(mocktail): remove dependency on `package:test`

---

packages/mocktail/CHANGELOG.md
packages/mocktail/pubspec.yaml

**READY**
NO
- chore(mocktail): v1.0.1

chore(mocktail): v1.0.1

---

packages/mocktail/pubspec.yaml

**READY**
NO
Allows to use the latest `test` package alongside mocktail.

chore(deps): allow `pkg:test_api >=0.7.0`

---

packages/mocktail/CHANGELOG.md
packages/mocktail/pubspec.yaml

**READY**
NO
- chore(mocktail): v1.0.2

chore(mocktail): v1.0.2

---

packages/mocktail/README.md

**READY**
NO
Last week I messed a lot trying to validate a method that received a parameter type outside my control was called. As that type didn't have equals overridden, mocktail never detected that the parameter was passed. So I had to use another strategy to check if that parameter was passed: to specify which attributes of the type to check.
I'm adding that strategy here as an example to help others. It's actually not mocktail documentation, but mocktail can also use that strategy, so it will save lives.

docs(mocktail): update `README.md` to include `any(that: ...)`

---

packages/mocktail/CHANGELOG.md
packages/mocktail/pubspec.yaml

**READY**
NO
- chore(mocktail): v1.0.3

chore(mocktail): v1.0.3

---

packages/mocktail_image_network/CHANGELOG.md
packages/mocktail_image_network/pubspec.yaml

**READY**
NO
- chore(mocktail_image_network): v1.2.0

chore(mocktail_image_network): v1.2.0

---

analysis_options.yaml
packages/mocktail/lib/src/mocktail.dart

**READY**
NO
- refactor(mocktail): upgrade `analysis_options.yaml`

refactor(mocktail): upgrade `analysis_options.yaml`

---

packages/mocktail/CHANGELOG.md
packages/mocktail/pubspec.yaml

**READY**
NO
- chore(mocktail): v1.0.4

chore(mocktail): v1.0.4

---

packages/mocktail/pubspec.yaml
packages/mocktail_image_network/pubspec.yaml

**READY**
NO
- chore: add `funding` to `pubspec.yaml`

chore: add `funding` to `pubspec.yaml`
